# Singular Value Decomposition (SVD)

Singular Value Decomposition is one of the most fundamental results in linear algebra.  
It provides a way to factorize any matrix and understand the geometric structure of a linear transformation.

Suppose

$$
A \in \mathbb{R}^{m \times n}
$$

Then the Singular Value Decomposition theorem states that any matrix can be written as

$$
A = U \Sigma V^T
$$

where

- $U$ is an $m \times m$ orthogonal matrix
- $V$ is an $n \times n$ orthogonal matrix
- $\Sigma$ is an $m \times n$ diagonal matrix with non-negative entries.

The diagonal entries of $\Sigma$ are called **singular values**.

---

# Structure of the Decomposition

## Matrix $U$

$$
U = [u_1, u_2, \dots , u_m]
$$

The columns of $U$ form an orthonormal basis of $\mathbb{R}^m$.

$$
U^T U = I
$$

These vectors are called **left singular vectors**.

---

## Matrix $V$

$$
V = [v_1, v_2, \dots , v_n]
$$

The columns of $V$ form an orthonormal basis of $\mathbb{R}^n$.

$$
V^T V = I
$$

These vectors are called **right singular vectors**.

---

## Matrix $\Sigma$

The matrix $\Sigma$ has the form

$$
\Sigma =
\begin{bmatrix}
\sigma_1 & 0 & 0 & \dots \\
0 & \sigma_2 & 0 & \dots \\
0 & 0 & \sigma_3 & \dots
\end{bmatrix}
$$

where

$$
\sigma_1 \ge \sigma_2 \ge \sigma_3 \ge 0
$$

These values are called **singular values**.

---

# Relation with Eigenvalues

Consider the matrix

$$
A^T A
$$

This matrix is symmetric and positive semidefinite.  
Its eigenvalues are non-negative.

The singular values satisfy

$$
\sigma_i = \sqrt{\lambda_i(A^T A)}
$$

where $\lambda_i$ are the eigenvalues of $A^TA$.

The eigenvectors of $A^TA$ form the matrix $V$.

---

# Construction of SVD

To compute the SVD of a matrix $A$:

1. Compute the matrix

$$
A^T A
$$

2. Find eigenvalues and eigenvectors of $A^TA$.

3. The eigenvectors form the matrix $V$.

4. Singular values are

$$
\sigma_i = \sqrt{\lambda_i}
$$

5. Compute

$$
u_i = \frac{A v_i}{\sigma_i}
$$

to obtain columns of $U$.

6. Construct the diagonal matrix $\Sigma$ using singular values.

Then

$$
A = U \Sigma V^T
$$

---

# Rank and Singular Values

The number of non-zero singular values equals the rank of the matrix.

$$
\text{rank}(A) = r
$$

---

# SVD as a Sum of Rank-1 Matrices

The matrix can also be written as

$$
A = \sum_{i=1}^{r} \sigma_i u_i v_i^T
$$

Each term is a **rank-1 matrix**.

---







**Here is an numerical  example of how we can decompose a matrix**

In [ ]:
import numpy as np
from numpy.linalg import eigh, norm

In [ ]:
A = np.array([[-5,2,3],[2,5,1],[-3,1,-5]])

In [ ]:
A

array([[-5,  2,  3],
       [ 2,  5,  1],
       [-3,  1, -5]])

In [ ]:
A.T@A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [ ]:
eigenvalues, V = eigh(A.T@A)

In [ ]:
V

array([[ 0.26726124, -0.96362411,  0.        ],
       [ 0.80178373,  0.22237479,  0.5547002 ],
       [-0.53452248, -0.14824986,  0.83205029]])

In [ ]:
V[:,0]

array([ 0.26726124,  0.80178373, -0.53452248])

In [ ]:
u0 = A@V[:,0]/norm(A@V[:,0])
u1 = A@V[:,1]/norm(A@V[:,1])
u2 = A@V[:,2]/norm(A@V[:,2])

In [ ]:
U = np.array([u0,u1,u2]).T

In [ ]:
 U.T@A@V

array([[ 5.00000000e+00,  4.61927558e-17, -5.80878766e-17],
       [-3.24483433e-16,  6.24499800e+00,  1.06687423e-16],
       [-2.24630037e-16, -1.28454465e-17,  6.24499800e+00]])

In [ ]:
np.round(U.T@A@V, decimals=5)

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245,  0.   ],
       [-0.   , -0.   ,  6.245]])

In [ ]:
D = np.round(U.T@A@V, decimals=5)

In [ ]:
U@D@V.T

array([[-5.00000149,  2.00000098,  3.00000073],
       [ 2.0000003 ,  5.00000057,  1.00000101],
       [-3.00000119,  0.99999963, -5.00000114]])

In [ ]:
np.round(U@D@V.T, decimals=5)

array([[-5.,  2.,  3.],
       [ 2.,  5.,  1.],
       [-3.,  1., -5.]])

**There is another method of doing this SVD using library**

In [ ]:
import numpy as np

A = np.array([[-5,2,3],
              [2,5,1],
              [-3,1,-5]])

U,S,Vt = np.linalg.svd(A)

print("U =\n",U)
print("Singular values =",S)
print("V^T =\n",Vt)
print(U@np.diag(S)@Vt)

U =
 [[-0.57735027 -0.77151675  0.26726124]
 [-0.57735027  0.15430335 -0.80178373]
 [ 0.57735027 -0.6172134  -0.53452248]]
Singular values = [6.244998 6.244998 5.      ]
V^T =
 [[-0.         -0.5547002  -0.83205029]
 [ 0.96362411 -0.22237479  0.14824986]
 [-0.26726124 -0.80178373  0.53452248]]
[[-5.  2.  3.]
 [ 2.  5.  1.]
 [-3.  1. -5.]]
